use_frameworks!

platform :ios, '9.0'

target 'BaseUtility_Example' do
  pod 'BaseUtility', :path => '../'

  target 'BaseUtility_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
